name: aml-course
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - requests
  - jupyterlab
  - ipykernel
  - seaborn
  - networkx
  - tqdm
  - pip:
      - torch
      - torchvision
